    SELECT A.AUTHOR_ID,AUTHOR_NAME,B.CATEGORY,SUM(SALES*PRICE) AS TOTAL_SALES
    FROM BOOK B
    JOIN AUTHOR A
    ON B.AUTHOR_ID=A.AUTHOR_ID
    JOIN(SELECT *
    FROM BOOK_SALES 
    WHERE SALES_DATE LIKE '2022-01%') S
    ON S.BOOK_ID=B.BOOK_ID
    GROUP BY A.AUTHOR_ID,B.CATEGORY
    ORDER BY A.AUTHOR_ID ASC,B.CATEGORY DESC;