SELECT I.ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO I
LEFT JOIN (SELECT PARENT_ITEM_ID AS ITEM_ID, ITEM_ID AS UPGRADE_ID FROM ITEM_TREE) T
ON I.ITEM_ID=T.ITEM_ID
WHERE UPGRADE_ID IS NULL
ORDER BY I.ITEM_ID DESC;