SELECT P.PRODUCT_CODE,SUM(S.SALES_AMOUNT)*P.PRICE AS SALES
FROM OFFLINE_SALE S
LEFT JOIN PRODUCT P
ON S.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SUM(S.SALES_AMOUNT)*P.PRICE DESC,P.PRODUCT_CODE ASC
