SELECT A.ANIMAL_ID,A.NAME
FROM (
    SELECT I.ANIMAL_ID AS ANIMAL_ID,NAME,DATEDIFF(OUT_DATETIME,DATETIME) AS DIFF
    FROM ANIMAL_INS I
    LEFT JOIN (SELECT ANIMAL_ID,DATETIME AS OUT_DATETIME FROM ANIMAL_OUTS) O
    ON I.ANIMAL_ID=O.ANIMAL_ID
    WHERE O.OUT_DATETIME IS NOT NULL
) A
ORDER BY A.DIFF DESC
LIMIT 2;
