SELECT ID,
CASE 
    WHEN RANKED_DATA  <= 25 THEN 'LOW'
    WHEN RANKED_DATA> 25 AND RANKED_DATA <= 50 THEN 'MEDIUM'
    WHEN RANKED_DATA  > 50 AND RANKED_DATA <= 75 THEN 'HIGH'
    WHEN RANKED_DATA > 75 AND RANKED_DATA <= 100 THEN 'CRITICAL'
    ELSE 'NOVALUE'
END AS COLONY_NAME
FROM ECOLI_DATA 
JOIN (
    SELECT ID,PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY ASC)* 100 AS RANKED_DATA
    FROM ECOLI_DATA
) AS ranked_date
USING(ID)
ORDER BY ID ASC;