-- 코드를 입력하세요

SELECT U.USER_ID,NICKNAME,CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소',CONCAT(LEFT(TLNO,3),'-',SUBSTRING(TLNO,4,4),'-',SUBSTRING(TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_USER U
LEFT JOIN(
SELECT WRITER_ID,COUNT(*) AS COUNT
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
    ) B
ON U.USER_ID=B.WRITER_ID
WHERE B.COUNT>=3
ORDER BY U.USER_ID DESC;
