-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR,MONTH(SALES_DATE) AS MONTH,GENDER,COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
FROM ONLINE_SALE 
JOIN (
    SELECT USER_ID,GENDER
    FROM USER_INFO  
) AS A
USING(USER_ID)
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER ASC;
