SELECT NAME,DATETIME
FROM ANIMAL_INS I
LEFT JOIN(
    SELECT ANIMAL_ID,DATETIME AS OUT_DATETIME
    FROM ANIMAL_OUTS
) O
ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE OUT_DATETIME IS NULL
ORDER BY DATETIME ASC
LIMIT 3;
