# -- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS HOUR, IFNULL(COUNT(DATETIME),0) AS COUNT
# FROM ANIMAL_OUTS 
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR(DATETIME);

SELECT B.HOUR AS HOUR,COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT
JOIN(
    SELECT ROW_NUMBER() OVER (ORDER BY ANIMAL_ID ASC) -1 AS HOUR
    FROM ANIMAL_OUTS 
    LIMIT 24
)B
ON HOUR(A.DATETIME)=B.HOUR
GROUP BY B.HOUR;