SELECT ID, GENOTYPE,PARENT_GENOTYPE
FROM ECOLI_DATA A
LEFT JOIN (
    SELECT ID AS PARENT_ID,GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
) B
USING(PARENT_ID)
WHERE PARENT_GENOTYPE&GENOTYPE>=PARENT_GENOTYPE
ORDER BY ID ASC;
