-- 코드를 입력하세요
SELECT MCDP_CD AS 진료과코드,COUNT(DISTINCT PT_NO) AS 5월예약건수
FROM (
    SELECT MCDP_CD,PT_NO
    FROM APPOINTMENT
    WHERE YEAR(APNT_YMD)=2022 AND MONTH(APNT_YMD)=5
    ) AS A
GROUP BY MCDP_CD
ORDER BY COUNT(DISTINCT PT_NO),MCDP_CD ASC;

# SELECT *
#  FROM APPOINTMENT
#  WHERE YEAR(APNT_YMD)=2022 AND MONTH(APNT_YMD)=5