# SELECT A.CATEGORY,COUNT(*) AS PRODUCTS
# FROM (SELECT CASE WHEN PRODUCT_ID IN (1,2) THEN 'A1'
# WHEN PRODUCT_ID IN (3,4,5) THEN 'C3'
# WHEN PRODUCT_ID=6 THEN 'K1'
# END AS CATEGORY
# FROM PRODUCT ) AS A
# GROUP BY A.CATEGORY
# HAVING A.CATEGORY IS NOT NULL
# ORDER BY A.CATEGORY;

SELECT LEFT(PRODUCT_CODE,2) AS CATEGORY,COUNT(*) AS PRODUCTS
FROM PRODUCT 
GROUP BY LEFT(PRODUCT_CODE,2)
ORDER BY CATEGORY;