SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR,MAX_SIZE-SIZE_OF_COLONY AS YEAR_DEV,ID
FROM ECOLI_DATA D
LEFT JOIN
(
SELECT YEAR(DIFFERENTIATION_DATE) AS DIFFERENTIATION_YEAR,MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)

) M
ON YEAR(D.DIFFERENTIATION_DATE)=M.DIFFERENTIATION_YEAR
ORDER BY YEAR,YEAR_DEV;
# ON YEAR(D.DIFFERENTIATION_DATE)=M.YEAR(DIFFERENTIATION_DATE);