SELECT ID, FISH_NAME,LENGTH
FROM FISH_INFO F
LEFT JOIN (
    SELECT I.FISH_TYPE,MAX(LENGTH) AS MAX_LENGTH,FISH_NAME
           FROM FISH_INFO I LEFT JOIN FISH_NAME_INFO N
            ON I.FISH_TYPE=N.FISH_TYPE GROUP BY FISH_TYPE,FISH_NAME
) M
ON F.FISH_TYPE=M.FISH_TYPE
WHERE F.LENGTH=M.MAX_LENGTH AND LENGTH>10
ORDER BY ID ASC;
