SELECT FISH_COUNT,MAX_LENGTH,FISH_TYPE
FROM 
(SELECT FISH_TYPE,AVG(LENGTH) AS AVERAGE,MAX(LENGTH)AS MAX_LENGTH,COUNT(*) AS FISH_COUNT 
 FROM FISH_INFO 
 GROUP BY FISH_TYPE)
 AS A
WHERE AVERAGE>=33
ORDER BY FISH_TYPE;