-- 코드를 입력하세요
SELECT PRICE_GROUP*10000 AS PRICE_GROUP,COUNT(PRODUCT_ID) AS PRODUCTS
FROM  (
    SELECT PRODUCT_ID,FLOOR(PRICE/10000) AS PRICE_GROUP
    FROM PRODUCT
) AS A
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;
